name: Run Trading Algo

on:
  workflow_dispatch:
  schedule:
    # 9:08 AM IST = 03:38 AM UTC
    - cron: '38 3 * * 1-5'

jobs:
  run-algo:
    runs-on: ubuntu-latest
    environment: MyAlog

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Run Main Script
        env:
          PYTHONUNBUFFERED: "1"
          KOTAK_CONSUMER_KEY: ${{ secrets.KOTAK_CONSUMER_KEY }}
          KOTAK_MOBILE_NUMBER: ${{ secrets.KOTAK_MOBILE_NUMBER }}
          KOTAK_UCC: ${{ secrets.KOTAK_UCC }}
          KOTAK_MPIN: ${{ secrets.KOTAK_MPIN }}
          TOTP_SECRET_KEY: ${{ secrets.TOTP_SECRET_KEY }}
        run: |
          python -u main.py
